name: "dbt_project"
version: "1.0.0"
config-version: 2

profile: "dbt_project"

vars:
  'dbt_date:time_zone': 'America/Los_Angeles'

analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    +materialized: table
    +post-hook:
    - "{{ dagster.log_column_level_metadata() }}"
    ANALYTICS:
      +group: marketing-group
    CLEANED:
      +group: core-data-eng
      +tags: "all_cleanred_models"
    FORECASTING:
      +group: data-science
    MARKETING:
      +group: marketing-group

query-comment:
  comment: "snowflake_dagster_dbt_v1_opaque_id[[[{{ node.unique_id }}:{{ invocation_id }}]]]"
  append: true