version: 2

sources:
  - name: "RAW_DATA"
    tables:
      - name: "orders"
      - name: "users"
      - name: "location"
        meta:
          dagster:
            asset_key: ['location']
  - name: "FORECASTING"
    tables:
      - name: "predicted_orders"
