version: 2

sources:
  - name: "RAW_DATA"
    tables:
      - name: "orders"
      - name: "users"
      - name: "raw_location"
        meta:
          dagster:
            asset_key: ['raw_location']
  - name: "FORECASTING"
    tables:
      - name: "predicted_orders"
