name: Dagster Cloud Hybrid Deployment
on:
  push: # for full deployment
    branches:
      - "main"
  pull_request:  # for branch deployments
     types: [opened, synchronize, reopened, closed]

concurrency: 
  # Cancel in-progress deploys to main branch
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  DAGSTER_CLOUD_URL: "https://hooli.dagster.cloud"
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}

jobs:
  dagster-cloud-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Pre-run checks
        id: prerun
        uses: dagster-io/dagster-cloud-action/actions/utils/prerun@ci-new-commands

      - name: Checkout
        uses: actions/checkout@v3      
        if : steps.prerun.outputs.result != 'skip'
        with:
          ref: ${{ github.head_ref }}

      - name: Initialize build session
        id: ci-init
        if : steps.prerun.outputs.result != 'skip'
        uses: dagster-io/dagster-cloud-action/actions/utils/ci-init@ci-new-commands
        with:
          project_dir: .

      - name: Generate docker image tag
        id: generate-image-tag
        if : steps.prerun.outputs.result != 'skip'
        run: echo "IMAGE_TAG=$GITHUB_SHA-$GITHUB_RUN_ID" >> $GITHUB_ENV && echo $IMAGE_TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        if : steps.prerun.outputs.result != 'skip'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  us-west-2

      - name: Login to ECR
        if : ${{ steps.prerun.outputs.result != 'skip' }}
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and upload Docker image
        if : steps.prerun.outputs.result != 'skip'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: 764506304434.dkr.ecr.us-west-2.amazonaws.com/hooli-data-science-prod:${{ env.IMAGE_TAG }}

      - name: Update build session with image tag
        id: ci-set-build-output
        if : steps.prerun.outputs.result != 'skip'
        uses: dagster-io/dagster-cloud-action/actions/utils/dagster-cloud-cli@ci-new-commands
        with:
          command: "ci set-build-output --image-tag=$IMAGE_TAG"

      - name: Deploy to Dagster Cloud
        id: ci-deploy
        if : steps.prerun.outputs.result != 'skip'
        uses: dagster-io/dagster-cloud-action/actions/utils/dagster-cloud-cli@ci-new-commands
        with:
          command: "ci deploy"